export const CHANGE_PAGE_TITLE = "CHANGE_PAGE_TITLE";
export const IS_SHOW_NAVBAR = "IS_SHOW_NAVBAR";
export const IS_SUBPAGE = "IS_SUBPAGE";
export const CHANGE_GOOD_CHECKED = "CHANGE_GOOD_CHECKED";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREACE_CART_COUNT = "INCREACE_CART_COUNT";
export const DECREACE_CART_COUNT = "DECREACE_CART_COUNT";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";