export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_GOOD_SELECT = 'CHANGE_GOOD_SELECT';
export const IS_CHECKED_ALLSELECT = 'IS_CHECKED_ALLSELECT';
export const DELETE_CHECKED_GOODS = 'DELETE_CHECKED_GOODS';
export const INCREASE_GOOD_COUNT = 'INCREASE_GOOD_COUNT';
export const DECREASE_GOOD_COUNT = 'DECREASE_GOOD_COUNT';